### ISSUE TITLE
Favicon designen & in html implementieren 

### ISSUE THREAD

**Issue by aureliabeck** [ID-Start-Winter22/chat-team-04#16]
als .ico und in html code packen 

Link zu Dokumentation im Wiki:

**Comment by michellerabzowski** [comment]
.ico funktioniert

**Comment by aureliabeck** [comment]
Icon muss wieder geupdatet werden, wer übernimmt die neue Aufgabe eigentlich? @YannickH31 @michellerabzowski

**Comment by aureliabeck** [comment]
Ist drin aber funktioniert oben in Website Leiste nicht

**Comment by aureliabeck** [comment]
Ich verschiebe es zum Milestone Sprint 2, denke das hat jetzt nicht die höchste Priorität.

**Comment by michellerabzowski** [comment]
hat beides funktioniert, schlichtes Design, vllt. kann man noch was adden, aber sonst kann issue geschlossen werden.

bitte nochmal drüberschauen @YannickH31 und closen

**Comment by YannickH31** [comment]
Sieht gut aus :)

**Comment by michellerabzowski** [comment]
Link zum Wiki: https://github.com/ID-Start-Winter22/chat-team-04/wiki/Sprint-2#issue--16-s
