### ISSUE TITLE
TO DO ÜBERSICHT --> 16.12.22 Sprint 1

### ISSUE THREAD

**Issue by michellerabzowski** [ID-Start-Winter22/chat-team-04#17]
Am Ende des 1. Sprints steht ein lauffähiger interaktiver Prototyp Ihres Chatbots. Der lauffähige Prototyp besteht aus

- [x] einem variationsreichen natürlichen Dialog und
- [x] einen erkennbaren Chatbot Charakter
- [x] einem funktionierenden Backend, das einfache Logik enthält.
- [x] Es gibt in Ihrem Repository eine Wiki Seite zu Sprint 1.

Design:

- [x] Iterieren Sie weiter die bereits gestalteten Items (Look&Feel): Icon, Bot Name, Charakter und Tone-of-voice (Tonalität der Texte).
- [x] Entwickeln Sie eine kurze Geschichte über den Bot, analog zu einer Figur aus einem Spielfilm oder Theaterstück. 
- [x] Füllen Sie den Conversation Design Canvas und Worksheet (MVA - Minimum Viable Assistant) aus.
- [x] Entwickeln Sie variationsreiche, zu Ihrer Nutzenden-Gruppe und Charakter des Bots, passende Dialoge. Die Dialoge sollten, sowohl Ihr Thema, als auch Begrüßung, Fehlermeldungen, Fragen, Entschuldigungen, Informationen, Vorschläge, Zusammenfassung und visuelle Elemente (Bilder, emojis, gifs, ...) behandeln.
- [x] Dokumentieren bzw. verlinken Sie alle Arbeiten aus dem Bereich Design auf der Wiki Seite zu Sprint 1.

Informatik:

- [x] Sprint Planung: Das Sprint Ziel ist ein lauffähiger Chatbot mit einfachen Funktionen.
- [x]  Erstellen Sie den Milestone Sprint 1 in Ihrem GitHub Repository. 
- [x] Fügen Sie denjenigen Issues den Milestone Sprint 1 hinzu, die Sie in Sprint 1 bearbeiten können. Falls Issues zu umfangreich sind, erstellen Sie einfachere Issues. 
- [x] Weisen Sie jedes Issue mindestens einem Teammitglied zu (als Asignee ein Teammitglied auswählen).
- [x] Bearbeiten Sie jeweils Ihre Issues und dokumentieren Sie für jedes Issue in Ihrem Wiki auf der Sprint 1 Wiki Seite, wie Ihre Lösung aussieht. Schreiben Sie im Kommentar des Issues, wo die Dokumentation im Wiki zu finden ist. 
Wenn Sie ein Issue vollständig bearbeitet haben, weisen Sie das Issue einem anderen Teammitglied als Reviewer zu. Vermerken Sie im Kommentar mögliche Fragen oder Anmerkungen für das Review. Wenn das Review erfolgreich ist, kommentiert der/die Reviewer das Issue und schließt das Issue.

Abgabe:

- [x] Erstellen Sie in Ihrem GitHub Repository einen 'Tag' mit dem Namen 'Sprint1' um den Stand von Code und Dokumentation nach Sprint 1 zu kennzeichnen. Es wird Ihr Stand des Repositorys mit dem Tag 'Sprint1' gewertet.
Stellen Sie sicher, dass sich alle Teammitglieder in die Teamarbeit einbringen. 
- [x] Am Ende von Sprint 1 steht ein Sprint Review. Dieser wird am 16. Dezember während der Lehrveranstaltung durchgeführt. Beim Sprint Review führen Sie eine Demo des Chatbots vor.

**Comment by aureliabeck** [comment]
All done! Good luck for tomorrow !!!
