### ISSUE TITLE
Einleitendes Issue

### ISSUE THREAD

**Issue by michellerabzowski** [ID-Start-Winter22/chat-team-04#2]
## User Story:

Als Hobbymaler:in will ich immer inspiriert sein, um oft malen zu können und in keine Inspirationsblockade zu gelangen.

**Comment by aureliabeck** [comment]
Können wir dieses Issue bitte schließen? Genau wie die anderen ersten Issues...Die sind so ungenau und nicht zielführend? SOS @michellerabzowski review plz
