### ISSUE TITLE
Dialogplanung

### ISSUE THREAD

**Issue by michellerabzowski** [ID-Start-Winter22/chat-team-04#21]
Dialoge strukturieren und skizzieren bevor es in die Umsetzung geht

 Entwickeln Sie variationsreiche, zu Ihrer Nutzenden-Gruppe und Charakter des Bots, passende Dialoge. Die Dialoge sollten, sowohl Ihr Thema, als auch Begrüßung, Fehlermeldungen, Fragen, Entschuldigungen, Informationen, Vorschläge, Zusammenfassung und visuelle Elemente (Bilder, emojis, gifs, ...) behandeln

**Comment by aureliabeck** [comment]
Review: zusammen in voiceflow alle Dialoge gemacht, 
Link ist in Email 

@YannickH31 hat alle neuen Dialoge gleich in den Code gemacht  siehe commit 534ff02b9a207891d41d7580100377f1984b7ff4

fertig! toll!
