### ISSUE TITLE
neue Entwürfe Icon in Wiki machen 

### ISSUE THREAD

**Issue by aureliabeck** [ID-Start-Winter22/chat-team-04#22]
bitte als png ins wiki hochladen

**Comment by michellerabzowski** [comment]
Ich habe meine Entwürfe im Wiki hochgeladen

**Comment by michellerabzowski** [comment]
@YannickH31 hats auch schon gepostet

**Comment by aureliabeck** [comment]
Mein Entwurf ist jetzt auch im Wiki. Ich close das Issue!

Link: https://github.com/ID-Start-Winter22/chat-team-04/wiki/Chatbot-Designteil-Entwicklung#logo--entstehungsprozess
