### ISSUE TITLE
utter_kein_start

### ISSUE THREAD

**Issue by michellerabzowski** [ID-Start-Winter22/chat-team-04#23]
Als Nutzer:in möchte ich die Möglichkeit haben, nach der Erklärung vom Ablauf des Bots zu sagen, dass ich nicht anfangen will.

**Comment by aureliabeck** [comment]
Irgendjemand muss das noch in den Code implementieren. @YannickH31 @michellerabzowski

**Comment by michellerabzowski** [comment]
Hätte jetzt eine kurze Story dazu geschrieben. Bitte schauts drüber, ob es passt :)
review: @aureliabeck

**Comment by aureliabeck** [comment]
commit bd05ceffe47f807f9a7f63586da4240318693010

passt! klappt supi :)
