### ISSUE TITLE
#3 utter_erklärung start Buttons hinzufügen

### ISSUE THREAD

**Issue by aureliabeck** [ID-Start-Winter22/chat-team-04#24]
User Story: Als User möchte ich die Möglichkeit haben entweder eine Erklärung zum Chatbot zu bekommen oder diese zu Überspringen.

Implementierung mit Buttons (siehe Rasa Documentation) 

[Link zur Dokumentation im Wiki](https://github.com/ID-Start-Winter22/chat-team-04/wiki/Sprint-1#issue-3)

**Comment by aureliabeck** [comment]
Ist in Git gepusht, haben wir gemeinsam programmiert, Reviewer: @michellerabzowski

**Comment by aureliabeck** [comment]
Dokumentation im Wiki ist fertig: https://github.com/ID-Start-Winter22/chat-team-04/wiki/Sprint-1#issue-3

**Comment by michellerabzowski** [comment]
okay, hab die story mit no_start gemacht, kann nun geclosed werden
