### ISSUE TITLE
#1 alle mvg Dateien/Code entfernen, SH Dateien hinzufügen

### ISSUE THREAD

**Issue by YannickH31** [ID-Start-Winter22/chat-team-04#27]
Alle verbliebenen Dateien und Code vom MVG Chatbot müssen entfernt werden.

**Comment by aureliabeck** [comment]
Review: alles fertig siehe commit 1606619f478556eebe054947158d9cde15631fd2 und 15bfc3a6e86e8937af547ebdfc69900e61e45427

**Comment by YannickH31** [comment]
https://github.com/ID-Start-Winter22/chat-team-04/wiki/Sprint-1#issue-1
