### ISSUE TITLE
#7 Neuer StoryPath beim "No I dont know 16personalities" button + neuer Dialog in domain.yaml

### ISSUE THREAD

**Issue by YannickH31** [ID-Start-Winter22/chat-team-04#29]
Es muss ein neuer Story path erstellt werden, falls Nutzer auf "Nein, ich kenne den 16 personalities test nicht" klicken.

**Comment by aureliabeck** [comment]
Review: 
amazing! 
fertig siehe 652d92980d2fd21f9787408eeeefee4695b10750

**Comment by YannickH31** [comment]
https://github.com/ID-Start-Winter22/chat-team-04/wiki/Sprint-1#issue-7
