### ISSUE TITLE
#12 Slot intent my_personality_is syntax korrigieren

### ISSUE THREAD

**Issue by YannickH31** [ID-Start-Winter22/chat-team-04#30]
syntax beim Intent my_personality_is muss korrigiert werden.

**Comment by aureliabeck** [comment]
Review: fertig, siehe commit 1a7cf6097d49fe06a99e99ec12dba3036351bdd8

**Comment by YannickH31** [comment]
https://github.com/ID-Start-Winter22/chat-team-04/wiki/Sprint-1#issue-12
