### ISSUE TITLE
#10 store personality & dispatch custom message mit slot personality

### ISSUE THREAD

**Issue by aureliabeck** [ID-Start-Winter22/chat-team-04#31]
User Story: Als User:in möchte ich, dass der Bot sich meinen Persönlichkeitstypen merken kann, um mir später einen personalisierten Vorschlag zu machen. Außerdem soll er mir bestätigen können, was für ein Typ ich bin, nachdem ich es dem Bot geschrieben habe, um spätere Fehler in den custom Inspirationsvorschlägen zu vermeiden. 

Implementierung in Stories: neue action action_store_personality und action_yourTypeIs um User Pers.Typen in slot zu speichern und danach zu bestätigen (nach intent my_personality_type_is)

**Comment by aureliabeck** [comment]
ist implementiert, siehe commit 0719e43348b79133276e5b31d78d45823f2ac4cb 

muss erweitert werden: 
- customizen der antworten für jeden personality type 

reviewer @michellerabzowski bitte reviewen und wenn alles okay ist dann neues issue mit erweiterter implementierung

**Comment by aureliabeck** [comment]
Link zur Dokumentation im Wiki: https://github.com/ID-Start-Winter22/chat-team-04/wiki/Sprint-1#issue-10

**Comment by aureliabeck** [comment]
Für das Sprint 1 Review nur für einen Persönlichkeitstypen zum zeigen. @michellerabzowski und ich programmieren das jetzt und pushen dann.

**Comment by michellerabzowski** [comment]
okay! neues issue ist nun da
