### ISSUE TITLE
#14 custom Action für colour

### ISSUE THREAD

**Issue by YannickH31** [ID-Start-Winter22/chat-team-04#32]
Es muss eine custom action für die erste Frage nach der Farbe angelegt werden, sowie um den slot zu speichern. (+ einen Test durchführen ob das Speichern geklappt hat)

**Comment by aureliabeck** [comment]
bei mir hat das mit dem Pink noch nicht geklappt.. Issue offen lassen bitte :(

**Comment by aureliabeck** [comment]
Funktioniert jetzt, wir können es closen!

**Comment by YannickH31** [comment]
https://github.com/ID-Start-Winter22/chat-team-04/wiki/Sprint-1#issue-14
