### ISSUE TITLE
#13 action_yourTypeIs angepasst sodass für jeden slot custom anwort von dispatcher

### ISSUE THREAD

**Issue by aureliabeck** [ID-Start-Winter22/chat-team-04#33]
User Story: Als User:in möchte ich, dass der Bot meinen Persönlichkeitstypen speichert und diesen zurückgeben kann bzw. sich für den späteren Inspirationsvorschlag merkt. 

Implementierung sodass für jeden Persönlichkeitstypen in slot personality_type der vom User gewählte Typ zurückgegeben wird.

[Link zur Dokumentation im Wiki](https://github.com/ID-Start-Winter22/chat-team-04/wiki/Sprint-1#issue-13)

**Comment by aureliabeck** [comment]
Gepusht in commit 0719e43348b79133276e5b31d78d45823f2ac4cb
hier nur raw version ohne verschiedene Dialoge aber Verzweigung für verschiedene Typen ist implementiert 

Achtung: verschiedene Antworten für verschiedene Typen müssen noch ergänzt werden ! (neues Issue)

Reviewer: @YannickH31

**Comment by aureliabeck** [comment]
Link zur Dokumentation im Wiki: https://github.com/ID-Start-Winter22/chat-team-04/wiki/Sprint-1#issue-13

**Comment by YannickH31** [comment]
passt
