### ISSUE TITLE
#15 cust. action für Frage "Welchen Kunssti[...]" und action_store_style

### ISSUE THREAD

**Issue by aureliabeck** [ID-Start-Winter22/chat-team-04#34]
User Story: Als User möchte ich nach meinem Kunst-Stil-Geschmack gefragt werden und aus random generierten Stilen einen auswählen können. Dieser soll gespeichert werden, um später einen auf meine Präferenzen zugeschnittenen Inspirationsvorschlag zu generieren. 

Implementierung: cust. action für kunst stile (action_store_style) & random generator für buttons mit 3 stilen die sich bei jeder abfrage ändern, dispatcher der frage kunststile stellt

[Link zur Dokumentation im Wiki](https://github.com/ID-Start-Winter22/chat-team-04/wiki/Sprint-1#issue-15)

**Comment by aureliabeck** [comment]
commit  b3978f8bcbf566b60a9f5070f76581cca3099a93

Buttons mit random generierten Kunst-Stilen implementiert

**Comment by aureliabeck** [comment]
commit db6ecbf0d369e595b8e19027946b7f1cd599a72d
intents in einen zusammengefasst, payload von Buttons als intent = der gewählte intent/button direkt in slot {art_style} weitergegeben 

fertig soweit, vielleicht noch neues issue um auch bilder zu jedem artstyle hinzuzufügen? 

reviewer:  @michellerabzowski

**Comment by michellerabzowski** [comment]
Sieht super aus!
Ich erstelle dann mal ein neues Issue zu den Artstyles :)
