### ISSUE TITLE
#4 Personality Intents

### ISSUE THREAD

**Issue by michellerabzowski** [ID-Start-Winter22/chat-team-04#36]
User Story: Als User würde ich gerne jede Mögliche Personality, die einem auf "https://www.16personalities.com/de/personlichkeitstypen" zur Verfügung steht in diesem Chatbot angeben können, damit alle Persönlichkeiten erwähnt worden sind.

**Comment by aureliabeck** [comment]
**review**: 

in intents als example alle Persönlichkeitstypen eingefügt, funktioniert in Chatbot ✅
siehe dein commit 38cf1b9cf5fedfd6dafc38bda195a2742eb0e130

um typ auch als Slot zu speichern, neues Issue ( Issue #30 und Issue #31 )

amazing!

**Comment by michellerabzowski** [comment]
Link zum Wiki: https://github.com/ID-Start-Winter22/chat-team-04/wiki/Sprint-1#issue-4
