### ISSUE TITLE
#8 HTML CSS zur Website hinzufügen

### ISSUE THREAD

**Issue by michellerabzowski** [ID-Start-Winter22/chat-team-04#37]
User Story: Als User hätte ich gerne eine anschauliche Website, wenn ich mit dem Bot chatte, damit das Erlebnis mit dem Bot schöner wird. 

Implementierung: HMTL mit neuer CSS Datei

**Comment by michellerabzowski** [comment]
Ein Paar Veränderungen vorgenommen: commit: https://github.com/ID-Start-Winter22/chat-team-04/commit/c4987b3d275fc48a396c66f6c6f792d1d0c10789

**Comment by michellerabzowski** [comment]
Veränderungen an den Texten: commit: https://github.com/ID-Start-Winter22/chat-team-04/commit/949fb4555feddd53aeb4572fdb03bab09c2ea5a4

**Comment by YannickH31** [comment]
Sieht gut aus ^^

**Comment by aureliabeck** [comment]
Gut, weiter iterieren für Sprint 2 

Milestone geändert

**Comment by michellerabzowski** [comment]
Link zu Wiki für Sprint 1: https://github.com/ID-Start-Winter22/chat-team-04/wiki/Sprint-1#issue-4

**Comment by michellerabzowski** [comment]
@aureliabeck @YannickH31 ihr könntet nochmal drüberschauen, aber meiner Meinung nach können wirs jetzt so lassen, da wir uns lieber auf den Bot ansich konzentrieren sollten. Die Website sieht ja eig ganz schlicht aber dennoch passend zu Paige aus.

Wenn ihrs angeschaut habt, dann bitte schließt den Issue :)

**Comment by aureliabeck** [comment]
Alright! Passt!

**Comment by michellerabzowski** [comment]
Link zum Wiki: https://github.com/ID-Start-Winter22/chat-team-04/wiki/Sprint-2#issue--37-s
