### ISSUE TITLE
#11 Langen Persönlichkeitstypen auf 4 Buchstaben kürzen

### ISSUE THREAD

**Issue by michellerabzowski** [ID-Start-Winter22/chat-team-04#38]
Die zu langen Persönlichkeitstypen mit dem "-T" oder "-P" sind viel zu individuell und geben eigentlich auch keinen Mehrwert, dementsprechend soll der Input des Users nur auf die ersten 4 Buchstaben gekürzt werden, sodass nur die Main-Personalities angezeigt werden (z.B. INTJ statt INTJ-P)

**Comment by michellerabzowski** [comment]
Reviewer: @YannickH31 -> bitte drüberschauen und dann das Issue closen, wenns passt

**Comment by YannickH31** [comment]
Passt :)

**Comment by michellerabzowski** [comment]
Link zum Wiki: https://github.com/ID-Start-Winter22/chat-team-04/wiki/Sprint-1#issue-11
