### ISSUE TITLE
form_question3 -> Bilder mit Buttons kombinieren

### ISSUE THREAD

**Issue by michellerabzowski** [ID-Start-Winter22/chat-team-04#39]
User Story: Als User hätte ich gerne im Bot eine Veranschaulichung der "Back"formen die ich wählen kann, damit eine Abwechslung entsteht, neben so viel Text.

**Comment by aureliabeck** [comment]
Fraglich ist, ob wir das im Rasa Webchat so implementieren können. Bis jetzt hab ich es nur mit einem carrousel in ner custom action probiert mit dem dispatcher und das hat leider nicht geklappt. (Habs nicht gepusht)

Hat jemand noch andere Ideen, wie wir das machen könnten? 

Für die Sprint 1 Präsenation lösen wir es jetzt einfach mit 1 Bild wo 4 nummerierte Formen drauf sind und 4 passenden nummerierten Buttons, right?

**Comment by michellerabzowski** [comment]
@aureliabeck, ja für Sprint 1 machen wir das erstmal so, und kümmern uns danach um eine elegantere Lösung

**Comment by aureliabeck** [comment]
Link zur Dokumentation im Wiki: https://github.com/ID-Start-Winter22/chat-team-04/wiki/Sprint-2#issue--39-a
