### ISSUE TITLE
Individuelle Vorschläge

### ISSUE THREAD

**Issue by michellerabzowski** [ID-Start-Winter22/chat-team-04#4]
## User Story: 
Ich will als Nutzer:in von Ideengeneratoren zufällige offene Fragen gestellt bekommen, um ein individuelles Ergebnis zu erhalten.

**Comment by aureliabeck** [comment]
Review:

Fragen nach Kunsstilen, Farben und random Formen wurden implementiert.
Der letztendliche Vorschlag muss noch implementiert werden, aber Antworten von User sind bereits in Slots gespeichert.
