### ISSUE TITLE
GIFS und Images in Dialog hinzufügen

### ISSUE THREAD

**Issue by michellerabzowski** [ID-Start-Winter22/chat-team-04#41]
Einige passende GIFs oder Bilder zu den Dialogen von dem Bot hinzufügen (z.B. wenn sie traurig ist oder besonders happy...)

**Comment by aureliabeck** [comment]
Habe ein Pinterest Board gepublished, jeder kann da mal paar Sachen pinnen damit wir uns auf ne Ästhetik einigen können! 

Link: https://pin.it/bx3SVwR

**Comment by aureliabeck** [comment]
Fertig, kein Review nötig. Alles zusammen besprochen.

Dokumentation: https://github.com/ID-Start-Winter22/chat-team-04/wiki/Sprint-2#issue--41-y
