### ISSUE TITLE
Customized Antwort für pers_type slot 

### ISSUE THREAD

**Issue by aureliabeck** [ID-Start-Winter22/chat-team-04#43]
für jeden Typen passende / quirky Antwort nachdem man seinen personality typ angibt

implementieren mit custom action bzw in vorhandene custom action

**Comment by aureliabeck** [comment]
Haben wir erledigt für 3 personality types (reicht für präsentation)

 Review: @YannickH31

**Comment by YannickH31** [comment]
Ist gut 👍🏻
