### ISSUE TITLE
Dialog inhaltlich verbessern 

### ISSUE THREAD

**Issue by aureliabeck** [ID-Start-Winter22/chat-team-04#46]
nach Review: Kritik an Dialogen => spannender machen und tlw kürzen und \n öfter einfügen + Bilder adden

**Comment by michellerabzowski** [comment]
Dialoge wurden persönlicher und auch personalisierter an Paige angepasst. Auch einige Imgs und GIFs sind zu finden. Emojis wurden eingefügt, um ihre Reaktion besser zu präsentieren. 

Reviewer: @aureliabeck

**Comment by aureliabeck** [comment]
Passt alles! Nur könnten wir nochmal diese "Deine Form ist" / "Deine Farbe ist.." bisschen besser formulieren.

**Comment by aureliabeck** [comment]
Alles fertig !

**Comment by michellerabzowski** [comment]
Link zum Wiki: https://github.com/ID-Start-Winter22/chat-team-04/wiki/Sprint-2#issue--46-s
