### ISSUE TITLE
Logo/Schriftlogo weiter iterieren

### ISSUE THREAD

**Issue by michellerabzowski** [ID-Start-Winter22/chat-team-04#47]
Weiter am Logo arbeiten, kleine oder auch große Veränderungen angehen.. Kreativität ausüben

**Comment by michellerabzowski** [comment]
Logo wurde minimal noch angepasst, nur Details wie Farbe oder Größe. 

Also bleiben wir dabei? -> Reviewen bitte: @aureliabeck @YannickH31

**Comment by aureliabeck** [comment]
Denke unser Logo passt jetzt. I like it! Great work!

**Comment by michellerabzowski** [comment]
Link zum Wiki: https://github.com/ID-Start-Winter22/chat-team-04/wiki/Sprint-2#issue--47-s
